SET FOREIGN_KEY_CHECKS=0;

LOAD DATA INFILE 'Item.tsv' REPLACE INTO TABLE Item FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Arma.tsv' REPLACE INTO TABLE Arma FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Mostro.tsv' REPLACE INTO TABLE Mostro FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'AreaInfernale.tsv' REPLACE INTO TABLE AreaInfernale FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Regione.tsv' REPLACE INTO TABLE Regione FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'ItemDrop.tsv' REPLACE INTO TABLE ItemDrop FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'MostroLeggendario.tsv' REPLACE INTO TABLE MostroLeggendario FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'MostroInfernale.tsv' REPLACE INTO TABLE MostroInfernale FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Origine.tsv' REPLACE INTO TABLE Origine FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Localita.tsv' REPLACE INTO TABLE Localita FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'LocalitaOstile.tsv' REPLACE INTO TABLE LocalitaOstile FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Faglia.tsv' REPLACE INTO TABLE Faglia FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'InsediamentoAbitato.tsv' REPLACE INTO TABLE InsediamentoAbitato FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Eroe.tsv' REPLACE INTO TABLE Eroe FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'GodSlayer.tsv' REPLACE INTO TABLE GodSlayer FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'SquadraAttuale.tsv' REPLACE INTO TABLE SquadraAttuale FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'SquadraPassata.tsv' REPLACE INTO TABLE SquadraPassata FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'MembroPassato.tsv' REPLACE INTO TABLE MembroPassato FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Boss.tsv' REPLACE INTO TABLE Boss FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'ArmaUnica.tsv' REPLACE INTO TABLE ArmaUnica FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Mercante.tsv' REPLACE INTO TABLE Mercante FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'InVendita.tsv' REPLACE INTO TABLE InVendita FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Habitat.tsv' REPLACE INTO TABLE Habitat FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Inventario.tsv' REPLACE INTO TABLE Inventario FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

LOAD DATA INFILE 'Appartenenza.tsv' REPLACE INTO TABLE Appartenenza FIELDS TERMINATED BY '\t' ENCLOSED BY "'";

SET FOREIGN_KEY_CHECKS=1;
